language: ruby
rvm:
- 2.3

before_script:
 - chmod +x travis.sh

before_install:
 - gem install bundler
#  - gem update --system

script: ./travis.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master
