# main text of home
name: Tom Lee
bio: A Boy who obesses over caffeine and vanilla ice cream

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: https://bwdmonkey.dev
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
linkedin: leesw16
github: bwdmonkey
email: seungwon.tom.lee@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
